# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ZainAutomotiveSolution' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ZainAutomotiveSolution
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/UI
  pod 'Firebase/Firestore'
  pod 'Cosmos', '~> 19.0'
  pod 'GoogleSignIn'

end
