# Uncomment the next line to define a global platform for your project
#platform :ios, '9.0'

target 'ZainAutomotiveSolution' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  

  # Pods for ZainAutomotiveSolution
  pod 'Eureka'
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'FirebaseUI', '~> 5.0'
  pod 'Firebase/Firestore'
  pod 'Cosmos', '~> 19.0'
  pod 'GoogleSignIn'
  pod 'JTAppleCalendar', '~> 7.1'
  pod 'MessageKit'
  
end

